### ISSUE TITLE
[2pts] Collaborative Project: Agile Development with a Skilled Team

### ISSUE THREAD

**Issue by Outkarm** [Ezzywealth/cab_bookings_frontend#1]
This is a group project involving three partners. Each partner has a specific role and contributes to the overall project.

Kanban Board: You can find the Kanban board for this project [here](https://github.com/users/Ezzywealth/projects/9/views/1). The Kanban board provides an organized view of the project's tasks, their progress, and assignment.

Team Members:

1. @Ezzywealth:
   - Role: Team Member 1
   - Responsibilities: Ezzywealth plays a crucial role in the project as Team Member 1. They bring their expertise, skills, and dedication to contribute to the project's success. Ezzywealth's specific responsibilities and tasks are outlined on the Kanban board. They actively participate in the project's development, collaborate with the other team members, and ensure the timely completion of assigned tasks.

2. @AbdimulhinYussuf3675:
   - Role: Team Member 2
   - Responsibilities: AbdimulhinYussuf3675 is an integral part of the project as Team Member 2. Their skills and contributions complement the team's efforts. As Team Member 2, AbdimulhinYussuf3675 is assigned specific tasks on the Kanban board. They actively engage in the project's activities, collaborate with other team members, and work towards achieving the project goals within the defined timeline.

3. @Outkarm:
   - Role: Team Member 3
   - Responsibilities: Outkarm assumes the role of Team Member 3 in this project. Their active involvement and unique skill set contribute to the project's success. Outkarm's assigned tasks and responsibilities are clearly defined on the Kanban board. They actively collaborate with the other team members, complete their assigned tasks, and ensure effective communication within the team.
   
Click [here](https://docs.google.com/document/d/1ARIf9wg09Bhk7VroKESmAeKURPgB3qHzcaqUGK4P0Qo/edit?usp=sharing) to view team working agreement

By leveraging the skills, expertise, and collaborative efforts of these three team members, the project aims to achieve its objectives successfully. The Kanban board serves as a central hub for task management and tracking progress, allowing the team to work efficiently and transparently. Effective coordination, communication, and timely completion of tasks are key factors for the project's overall success.

## Screenshot
![image](https://github.com/Ezzywealth/cab_bookings_frontend/assets/108669691/7ac472f8-bc55-42ed-927b-2ab7decf4ca0)

Throughout the project, the team members remain committed to their assigned roles, actively contribute their skills and knowledge, and maintain a collaborative and professional working environment.

**Comment by Meltrust** [comment]
Hi team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.

Also, the link is set as private.  I can't access it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi TEAM,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)


Congratulations! 🎉 

### To highlight

- All cards have been assigned, pointed, and have descriptions✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
